modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "londonunderground"
version = "@version@"
displayName = "MTR London Underground Addon"
authors = "t1NbLu3"
description = "A London Underground Addon for the Minecraft Transit Railway Mod"
logoFile = "icon.png"

[[dependencies.londonunderground]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.londonunderground]]
modId = "minecraft"
mandatory = true
versionRange = "[@minecraft@]"
ordering = "NONE"
side = "BOTH"

[[dependencies.londonunderground]]
modId = "mtr"
mandatory = true
versionRange = "1.0"
ordering = "AFTER"
side = "BOTH"
